In [10]:
import numpy as np

- 1번

In [11]:
a = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

- 2번

In [12]:
m =  np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
#2-1)
m[1:2,2:3]

array([[7]])

In [14]:
#2-2)
m[-1:,-1:]

array([[14]])

In [15]:
#2-3)
m[1:2, 1:3]

array([[6, 7]])

In [20]:
#2-4)
m[1:,2:3].reshape(1,2)

array([[ 7, 12]])

In [22]:
#2-5)
m[:2,-2:]

array([[3, 4],
       [8, 9]])

- 3번

In [18]:
f = m.reshape(-1,)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- 3-1

In [24]:
np.where(f % 3 == 0)


(array([ 0,  3,  6,  9, 12], dtype=int64),)

- 3-2

In [25]:
np.where(f % 4 ==1)

(array([ 1,  5,  9, 13], dtype=int64),)

- 3-3

In [55]:
a = np.concatenate(np.where(f % 3 == 0) + np.where(f % 4 ==1))
a

array([ 0,  3,  6,  9, 12,  1,  5,  9, 13], dtype=int64)

In [56]:
np.unique(a)

array([ 0,  1,  3,  5,  6,  9, 12, 13], dtype=int64)

- 4 번

In [ ]:
np.eye(5,5, k=-1, dtype=int)*3 + np.eye(5, 5, k=0, dtype=int)*2 + np.eye(5,5, k=1, dtype=int) 

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

- 5번

In [ ]:
a = np.random.randint(0,10,30).reshape(5,6)
a

array([[2, 4, 7, 9, 2, 0],
       [5, 5, 6, 7, 9, 5],
       [8, 2, 4, 6, 5, 7],
       [7, 6, 1, 3, 2, 2],
       [2, 3, 0, 8, 8, 7]])

In [ ]:
#5-1
a.max()

9

In [ ]:
#5-2
a.sum(axis=1)

array([24, 37, 32, 21, 28])

In [ ]:
#5-3
a.max(axis=1)

array([9, 9, 8, 7, 8])

In [ ]:
#5-4
a.mean(axis=0)

array([4.8, 4. , 3.6, 6.6, 5.2, 4.2])

In [ ]:
#5-5
a.min(axis=0)

array([2, 2, 0, 3, 2, 0])

- 6번

In [ ]:
g = np.array([1,2,3,4])
e = np.array([46,99,100,71])
m = np.array([81,59,90,100])


In [ ]:
np.argsort(e)


array([0, 3, 1, 2], dtype=int64)

In [ ]:
e[[0, 3, 1, 2][::-1]]

array([100,  99,  71,  46])

In [ ]:
array1 = e[[0, 3, 1, 2][::-1]]
array2 = g[[0, 3, 1, 2][::-1]]
array3 = m[[0, 3, 1, 2][::-1]]

new_score = np.array([[array2],[array1],[array3]]).reshape(3,4)
new_score

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

- 7번

In [ ]:
# 사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
# 던져서 나오는 숫자의 평균을 구하시오.

a = np.random.randint(1,7,100)
a.mean()

3.23

- 8번

In [ ]:
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 
# 250일 동안의 주가를 무작위로 생성하시오.


In [ ]:
# 수익률 = (기대값 0%, 표준편차가 1%)
# 정규분포 : N(평균, 표준편차, 갯수)
np.random.normal(10000,1,250)  

array([ 9996.47072778, 10000.80210669,  9999.42595266,  9999.38299192,
       10001.27373122, 10000.0352225 ,  9999.89534863, 10000.2776047 ,
        9999.34428624,  9999.91202169, 10000.30295574,  9999.33590731,
        9999.85724424, 10001.19371687, 10000.63098965, 10000.20150703,
       10000.20768957, 10002.05758629,  9999.44455847, 10001.60584289,
       10001.73885345, 10000.9076155 ,  9999.46813828, 10000.63246701,
        9999.76425936, 10001.23078118,  9998.71393274, 10000.79345383,
        9999.61180502,  9999.33866082,  9999.74541502,  9999.81848108,
        9999.78798315, 10002.06138686,  9998.88803446, 10000.04670121,
        9999.74155133, 10000.7167814 ,  9998.22465202, 10002.63894341,
       10000.11347265,  9997.66402966,  9999.30824298, 10000.16576839,
       10000.48588446, 10001.71523216, 10000.17497248,  9999.84702536,
        9998.41784039,  9999.64308077, 10000.15905129,  9999.89162901,
       10000.46493683,  9999.75182028,  9998.79040562,  9999.3001095 ,
      