In [61]:
import numpy as np

- 1번

In [11]:
a = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [62]:
a = np.arange(1,9).reshape(2,4)*10
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [63]:
a = np.arange(10,81,10).reshape(2,4)

- 2번

In [12]:
m =  np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
#2-1)
m[1:2,2:3]

array([[7]])

In [14]:
#2-2)
m[-1:,-1:]

array([[14]])

In [64]:
#2-3)
m[1, 1:3]

array([6, 7])

In [65]:
#2-3)을 이차원으로 만드려면
m[1:2, 1:3]

array([[6, 7]])

In [20]:
#2-4)
m[1:,2:3].reshape(1,2)

array([[ 7, 12]])

In [68]:
#2-4) 강사님
m[1:, 2]

array([ 7, 12])

In [22]:
#2-5)
m[:2,-2:]

array([[3, 4],
       [8, 9]])

- 3번

In [18]:
f = m.reshape(-1,)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- 3-1

In [24]:
np.where(f % 3 == 0)


(array([ 0,  3,  6,  9, 12], dtype=int64),)

In [70]:
f[f%3 ==0]

array([ 0,  3,  6,  9, 12])

- 3-2

In [71]:
f[f % 4 ==1]

array([ 1,  5,  9, 13])

- 3-3

In [55]:
a = np.concatenate(np.where(f % 3 == 0) + np.where(f % 4 ==1))
a

array([ 0,  3,  6,  9, 12,  1,  5,  9, 13], dtype=int64)

In [76]:
#강사님
f[np.logical_and(f%3==0, f%4==1)]

array([9])

In [75]:
#9값만 빼오고 싶을때
f[np.logical_and(f%3==0, f%4==1)][0]

9

In [56]:
np.unique(a)

array([ 0,  1,  3,  5,  6,  9, 12, 13], dtype=int64)

- 4 번

In [ ]:
np.eye(5,5, k=-1, dtype=int)*3 + np.eye(5, 5, k=0, dtype=int)*2 + np.eye(5,5, k=1, dtype=int) 

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [79]:
#강사님답   eye(N(행),M(열),k, dtype=)
np.eye(5,5,1,int)*3 + np.eye(5, 5,0, int)*2 + np.eye(5,5,1,int) 

array([[2, 4, 0, 0, 0],
       [0, 2, 4, 0, 0],
       [0, 0, 2, 4, 0],
       [0, 0, 0, 2, 4],
       [0, 0, 0, 0, 2]])

- 5번

In [82]:
np.random.seed(2022)
m= np.random.uniform(0,10,30).reshape(5,6).round(4)  #round 소숫점 자리수
m

array([[0.0936, 4.9906, 1.1338, 0.4997, 6.8541, 4.8699],
       [8.9766, 6.4745, 8.9696, 7.2113, 8.3135, 8.2757],
       [8.3358, 9.5704, 3.6804, 4.9484, 3.3951, 6.1943],
       [9.7753, 0.9643, 7.4421, 2.925 , 2.9868, 7.5247],
       [0.1866, 5.2374, 8.6444, 3.8884, 2.1219, 4.7518]])

In [84]:
m.max()

9.7753

In [85]:
a = np.random.randint(0,10,30).reshape(5,6)
a

array([[5, 0, 7, 5, 5, 8],
       [2, 4, 0, 9, 4, 9],
       [8, 8, 0, 3, 9, 5],
       [2, 1, 7, 2, 1, 7],
       [9, 6, 6, 7, 2, 9]])

In [83]:
#5-1
a.max()

80

In [ ]:
#5-2
a.sum(axis=1)

array([24, 37, 32, 21, 28])

In [ ]:
#5-3
a.max(axis=1)

array([9, 9, 8, 7, 8])

In [ ]:
#5-4
a.mean(axis=0)

array([4.8, 4. , 3.6, 6.6, 5.2, 4.2])

In [ ]:
#5-5
a.min(axis=0)

array([2, 2, 0, 3, 2, 0])

- 6번

In [88]:
g = np.array([1,2,3,4])
e = np.array([46,99,100,71])
m = np.array([81,59,90,100])


In [89]:
np.argsort(e)


array([0, 3, 1, 2], dtype=int64)

In [90]:
array1 = e[[0, 3, 1, 2][::-1]]
array2 = g[[0, 3, 1, 2][::-1]]
array3 = m[[0, 3, 1, 2][::-1]]


new_score = np.array([[array2],[array1],[array3]]).reshape(3,4)
new_score

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [92]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])

In [93]:
indices = np.argsort(score[1])

In [94]:
indices[::-1]
score[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [95]:
#한줄로
score[:,np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

- 7번

In [98]:
# 사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
# 던져서 나오는 숫자의 평균을 구하시오.

dice = np.random.randint(1,7,100)
dice.mean()

3.47

In [99]:
#dice array에서 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [102]:
##dice array에서 고유값 및 그 갯수
unique, counts = np.unique(dice,return_counts=True)
dict(zip(unique, counts))

{1: 18, 2: 12, 3: 19, 4: 20, 5: 18, 6: 13}

- 8번

In [ ]:
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 
# 250일 동안의 주가를 무작위로 생성하시오.


In [103]:
np.random.seed(2022)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [106]:
#위에서 구한 이자율(%)
rate * 100

array([-5.27899086e-04, -2.74901425e-01, -1.39285562e-01,  1.98468616e+00,
        2.82109326e-01])

In [112]:
#250개 리스트로 만드는것
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []

for i in range(250):
    price = price + np.round(price *rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]


array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [ ]:
#250개 어레이로 만드는것
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

In [ ]:
#randn
np.random.seed(2022)
rate = np.random.randn(250)
price = 10000
price_array = np.empty(250,dtype=np.int32)

for i in range(250):
    price = price + np.round(price * (1 + rate[i]))
    price_array[i] = price

price_array = np.array(price_list, dtype=np.int32)

In [ ]:
# 수익률 = (기대값 0%, 표준편차가 1%)
# 정규분포 : N(평균, 표준편차, 갯수)
np.random.normal(10000,1,250)  

array([ 9996.47072778, 10000.80210669,  9999.42595266,  9999.38299192,
       10001.27373122, 10000.0352225 ,  9999.89534863, 10000.2776047 ,
        9999.34428624,  9999.91202169, 10000.30295574,  9999.33590731,
        9999.85724424, 10001.19371687, 10000.63098965, 10000.20150703,
       10000.20768957, 10002.05758629,  9999.44455847, 10001.60584289,
       10001.73885345, 10000.9076155 ,  9999.46813828, 10000.63246701,
        9999.76425936, 10001.23078118,  9998.71393274, 10000.79345383,
        9999.61180502,  9999.33866082,  9999.74541502,  9999.81848108,
        9999.78798315, 10002.06138686,  9998.88803446, 10000.04670121,
        9999.74155133, 10000.7167814 ,  9998.22465202, 10002.63894341,
       10000.11347265,  9997.66402966,  9999.30824298, 10000.16576839,
       10000.48588446, 10001.71523216, 10000.17497248,  9999.84702536,
        9998.41784039,  9999.64308077, 10000.15905129,  9999.89162901,
       10000.46493683,  9999.75182028,  9998.79040562,  9999.3001095 ,
      